
package:
  name: tnt
  version: 126

source:
  fn: master.zip
  url: https://github.com/USGS-Astrogeology/TNT/archive/master.zip
  patches: patches/tnt_fix.patch

build:
  number: 1

about:
  home: http://math.nist.gov/tnt/
  license: public domain
  summary: collection of interfaces and reference implementations
    of numerical objects useful for scientific computing in C++.

extra:
  recipe-maintainers:
    - rbogle
